# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
### DEBUG script for the SOCA simplex method ########
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# This script allows for debugging and testing the SOCA Simplex method on specific:
# - Date (current_date)
# - Target (ILI incidence, ARI incidence, case, death, hosp)
# - Country (specific country or all countries)
# 
# Script generated by copilot, based on original code by Rok Grah and Eva Bons
# ECDC Mathematical Modelling Team
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
### LOAD REQUIRED LIBRARIES ########
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
library(tidyverse)
library(lubridate)

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
### USER CONFIGURATION ########
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# REQUIRED PARAMETERS - MODIFY THESE
current_date <- ymd("2025-10-27")  # Must be a Monday
target_to_run <- "hosp"   # Options: "ILI incidence", "ARI incidence", "case", "death", "hosp"
country_filter <- "PT"       # Specific country code or "ALL" for all countries

# OPTIONAL PARAMETERS - MODIFY IF NEEDED
verbose_output <- TRUE            # Print detailed progress messages
plot_results <- TRUE             # Generate and save plots
save_files <- FALSE              # Save output CSV files (set to FALSE for debugging)
E_vec <- c(8) #seq(2, 8)               # Pattern lengths to test (seq(2,8))
transform_vec <- c("delta-log-weekly") # default: c("weekly", "delta-weekly", "log-weekly", "delta-log-weekly")

# Advanced debugging options
debug_simplex_compute <- FALSE    # Add debugging to simplex_compute function
show_intermediate_results <- TRUE # Show intermediate computation results

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
### VALIDATION AND SETUP ########
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Validate current_date is Monday
if (weekdays(current_date) != "Monday") {
  stop("ERROR: current_date must be a Monday. You provided: ", weekdays(current_date))
}

# Validate target
valid_targets <- c("ILI incidence", "ARI incidence", "case", "death", "hosp")
if (!target_to_run %in% valid_targets) {
  stop("ERROR: target_to_run must be one of: ", paste(valid_targets, collapse = ", "))
}

if (verbose_output) {
  message("=== SOCA SIMPLEX DEBUG SESSION ===")
  message("Date: ", current_date)
  message("Target: ", target_to_run)
  message("Country: ", country_filter)
  message("E values: ", paste(E_vec, collapse = ", "))
  message("Transform types: ", paste(transform_vec, collapse = ", "))
  message("Plot results: ", plot_results)
  message("Save files: ", save_files)
  message("=====================================")
}

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
### LOAD LIBRARIES AND FUNCTIONS ########
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

if (verbose_output) message("Loading libraries and functions...")

# Load standard ECDC used packages and libraries
library(fitdistrplus)
library(devtools)

# Load other support packages
library(scoringutils)
library(hubVis)
library(data.table)
library(pracma)
library(here)

# set working directory to script location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

# Source relevant functions
source("run_ILI_ARI.R")
source("run_COVID_targets.R")
source("estimate_simplex_WIS.R")
source("simplex_compute.R")
source("../../plot_data_with_quantiles.R")

# Function that returns values from a that are not in b
relcomp <- function(a, b) {
  comp <- vector()
  for (i in a) {
    if (i %in% a && !(i %in% b)) {
      comp <- append(comp, i)
    }
  }
  return(comp)
}

# Enhanced debugging wrapper for simplex_compute if debugging is enabled
if (debug_simplex_compute) {
  # Store original function
  original_simplex_compute <- simplex_compute
  
  # Create debugging wrapper
  simplex_compute <- function(df_train, dates_to_forecast_from, E_vec, country_list, transform_vec, target) {
    message("DEBUG: Calling simplex_compute with:")
    message("  - Target: ", target)
    message("  - Countries: ", paste(country_list, collapse = ", "))
    message("  - E values: ", paste(E_vec, collapse = ", "))
    message("  - Transform types: ", paste(transform_vec, collapse = ", "))
    message("  - Forecast dates: ", paste(dates_to_forecast_from, collapse = ", "))
    
    result <- original_simplex_compute(df_train, dates_to_forecast_from, E_vec, country_list, transform_vec, target)
    
    message("DEBUG: simplex_compute completed. Result dimensions: ", nrow(result), " x ", ncol(result))
    return(result)
  }
}

if (verbose_output) message("✓ Libraries and functions loaded successfully")

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
### LOAD AND PREPARE DATA ########
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

if (verbose_output) message("Loading and preparing data for target: ", target_to_run)

countries_EU <- c("Austria", "Croatia", "Denmark", "France", "Greece", 
                  "Ireland", "Latvia", "Romania", "Spain", "Belgium", 
                  "Bulgaria", "Cyprus", "Czechia", "Estonia", "Finland",  
                  "Germany", "Hungary", "Iceland", "Italy", "Liechtenstein", 
                  "Lithuania", "Luxembourg", "Malta", "Netherlands", "Norway", 
                  "Poland", "Portugal", "Slovakia", "Slovenia", "Sweden")

# Load data based on target
if (target_to_run %in% c("ILI incidence", "ARI incidence")) {
  
  # Load ILI data
  if (target_to_run == "ILI incidence" || target_to_run == "ARI incidence") {
    if (verbose_output) message("Loading ILI data...")
    df_all_ILI <- read.csv("https://raw.githubusercontent.com/european-modelling-hubs/RespiCast-SyndromicIndicators/refs/heads/main/target-data/latest-ILI_incidence.csv") %>%
      rename(date = truth_date)
    
    df_train_ILI <- df_all_ILI %>% 
      filter((date < "2019-12-01" & date > "2015-10-01") | (date > "2022-10-01")) %>%
      arrange(location, date) %>%
      group_by(location) %>%
      mutate(value = ifelse(value == 0, 1e-3, value)) %>%
      mutate(value_diff = c(NA, diff(value))) %>%
      mutate(value_log = log10(value)) %>%
      mutate(value_log_diff = c(NA, diff(value_log))) %>%
      ungroup()
  }
  
  # Load ARI data
  if (target_to_run == "ARI incidence") {
    if (verbose_output) message("Loading ARI data...")
    df_all_ARI <- read.csv("https://raw.githubusercontent.com/european-modelling-hubs/RespiCast-SyndromicIndicators/refs/heads/main/target-data/latest-ARI_incidence.csv") %>%
      rename(date = truth_date)
    
    df_train_ARI <- df_all_ARI %>% 
      filter((date < "2019-12-01" & date > "2015-10-01") | (date > "2022-10-01")) %>%
      arrange(location, date) %>%
      group_by(location) %>%
      mutate(value = ifelse(value == 0, 1e-3, value)) %>%
      mutate(value_diff = c(NA, diff(value))) %>%
      mutate(value_log = log10(value)) %>%
      mutate(value_log_diff = c(NA, diff(value_log))) %>%
      ungroup()
  }
  
  # Set appropriate dataframes
  if (target_to_run == "ILI incidence") {
    df_all <- df_all_ILI
    df_train <- df_train_ILI
  } else {
    df_all <- df_all_ARI
    df_train <- df_train_ARI
  }
  
} else {
  # COVID targets
  if (verbose_output) message("Loading COVID data...")
  
  path_data_cases <- "https://raw.githubusercontent.com/european-modelling-hubs/covid19-forecast-hub-europe/main/data-truth/ECDC/truth_ECDC-Incident%20Cases.csv"
  path_data_deaths <- "https://raw.githubusercontent.com/european-modelling-hubs/covid19-forecast-hub-europe/main/data-truth/ECDC/truncated_ECDC-Incident%20Deaths.csv"
  path_data_hosps <- "https://raw.githubusercontent.com/european-modelling-hubs/RespiCast-Covid19/refs/heads/main/target-data/ERVISS/latest-hospital_admissions.csv"
  
  if (target_to_run == "case") {
    df_all_cases <- read.csv(path_data_cases) %>%
      rename(date = target_end_date)
    
    df_train_cases <- df_all_cases %>%
      filter((date < "2020-03-01" & date > "2015-10-01") | (date > "2022-05-01")) %>%
      arrange(location, date) %>%
      group_by(location) %>%
      mutate(value = ifelse(value == 0, 1e-3, value)) %>%
      mutate(value_diff = c(NA, diff(value))) %>%
      mutate(value_log = log10(value)) %>%
      mutate(value_log_diff = c(NA, diff(value_log))) %>%
      ungroup()
    
    df_all <- df_all_cases
    df_train <- df_train_cases
    
  } else if (target_to_run == "death") {
    df_all_deaths <- read.csv(path_data_deaths) %>%
      rename(date = target_end_date)
    
    df_train_deaths <- df_all_deaths %>%
      filter((date < "2020-03-01" & date > "2015-10-01") | (date > "2022-05-01")) %>%
      arrange(location, date) %>%
      group_by(location) %>%
      mutate(value = ifelse(value == 0, 1e-3, value)) %>%
      mutate(value_diff = c(NA, diff(value))) %>%
      mutate(value_log = log10(value)) %>%
      mutate(value_log_diff = c(NA, diff(value_log))) %>%
      ungroup()
    
    df_all <- df_all_deaths
    df_train <- df_train_deaths
    
  } else if (target_to_run == "hosp") {
    df_all_hosps <- read.csv(path_data_hosps) %>%
      rename(date = truth_date)
    
    df_train_hosps <- df_all_hosps %>%
      filter((date < "2020-03-01" & date > "2015-10-01") | (date > "2022-05-01")) %>%
      arrange(location, date) %>%
      group_by(location) %>%
      mutate(value = ifelse(value == 0, 1e-3, value)) %>%
      mutate(value_diff = c(NA, diff(value))) %>%
      mutate(value_log = log10(value)) %>%
      mutate(value_log_diff = c(NA, diff(value_log))) %>%
      ungroup()
    
    df_all <- df_all_hosps
    df_train <- df_train_hosps
  }
}

if (verbose_output) message("✓ Data loaded successfully")

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
### FILTER DATA BY COUNTRY ########
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Get available countries
available_countries <- unique(df_all$location)

if (country_filter != "ALL") {
  if (!country_filter %in% available_countries) {
    if (verbose_output) {
      message("Available countries for ", target_to_run, ":")
      message(paste(available_countries, collapse = ", "))
    }
    stop("ERROR: Country '", country_filter, "' not found in data for target '", target_to_run, "'")
  }
  
  # Filter data to specific country
  df_all <- df_all %>% filter(location == country_filter)
  df_train <- df_train %>% filter(location == country_filter)
  country_list <- country_filter
  
  if (verbose_output) message("✓ Data filtered for country: ", country_filter)
} else {
  country_list <- available_countries
  if (verbose_output) message("✓ Running for all available countries (", length(country_list), " countries)")
}

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
### SET UP FORECAST PARAMETERS ########
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Forecast dates: forecast for every week in the last 5 weeks
dates_to_forecast_from <- (current_date - 8) + c(-28, -21, -14, -7, 0)

if (verbose_output) {
  message("Forecast parameters:")
  message("  E vector (pattern lengths): ", paste(E_vec, collapse = ", "))
  message("  Transform types: ", paste(transform_vec, collapse = ", "))
  message("  Forecast dates: ", paste(dates_to_forecast_from, collapse = ", "))
  message("  Countries to process: ", length(country_list))
}

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
### RUN SOCA SIMPLEX METHOD ########
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

if (verbose_output) message("=== STARTING SOCA SIMPLEX COMPUTATION ===")

# Show data summary before processing
if (show_intermediate_results) {
  message("=== DATA SUMMARY ===")
  message("Training data:")
  message("  - Date range: ", min(df_train$date), " to ", max(df_train$date))
  message("  - Number of rows: ", nrow(df_train))
  message("  - Countries: ", paste(unique(df_train$location), collapse = ", "))
  
  # Show sample data for the specific country
  if (country_filter != "ALL") {
    sample_data <- df_train %>% 
      filter(location == country_filter) %>% 
      tail(10)
    message("Last 10 data points for ", country_filter, ":")
    print(sample_data %>% select(date, value))
  }
  message("==================")
}

# Call the appropriate function based on target
if (target_to_run %in% c("ILI incidence", "ARI incidence")) {
  
  result <- run_ILI_ARI(E_vec = E_vec,
                        transform_vec = transform_vec,
                        df_all = df_all,
                        df_train = df_train,
                        dates_to_forecast_from = dates_to_forecast_from,
                        country_list = country_list,
                        save_files = save_files,
                        target = target_to_run,
                        plot_results = plot_results)
  
} else {
  
  result <- run_COVID_targets(E_vec = E_vec,
                             transform_vec = transform_vec,
                             df_all = df_all,
                             df_train = df_train,
                             dates_to_forecast_from = dates_to_forecast_from,
                             country_list = country_list,
                             save_files = save_files,
                             target = target_to_run,
                             plot_results = plot_results,
                             log_optimal_pars = TRUE)
}

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
### DEBUG OUTPUT AND SUMMARY ########
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

if (verbose_output) {
  message("=== DEBUG SESSION COMPLETED ===")
  message("Target: ", target_to_run)
  message("Country: ", country_filter)
  message("Date: ", current_date)
  message("Files saved: ", save_files)
  message("Plots generated: ", plot_results)
  
  if (save_files) {
    date_submission <- current_date + 2
    if (target_to_run == "ILI incidence") {
      output_file <- paste0("Forecasting-hubs_models/model_output/Syndromic_indicators/ILI/", date_submission, "-ECDC-soca_simplex.csv")
    } else if (target_to_run == "ARI incidence") {
      output_file <- paste0("Forecasting-hubs_models/model_output/Syndromic_indicators/ARI/", date_submission, "-ECDC-soca_simplex.csv")
    } else {
      output_file <- paste0("Forecasting-hubs_models/model_output/COVID/", date_submission, "-ECDC-soca_simplex_", target_to_run, ".csv")
    }
    message("Output saved to: ", output_file)
  }
  
  if (plot_results) {
    date_submission <- current_date + 2
    if (target_to_run %in% c("ILI incidence", "ARI incidence")) {
      target_short <- ifelse(target_to_run == "ILI incidence", "ILI", "ARI")
      plot_file <- paste0("Forecasting-hubs_models/model_output/figures/", date_submission, "-ECDC-soca_simplex_", target_short, ".jpg")
    } else {
      plot_file <- paste0("Forecasting-hubs_models/model_output/figures/", date_submission, "-ECDC-soca_simplex_", target_to_run, ".jpg")
    }
    message("Plot saved to: ", plot_file)
  }
  
  message("=================================")
}

# Print success message
message("✓ SOCA Simplex debug run completed successfully for ", target_to_run, " - ", country_filter)
